language: java

os: linux

dist: xenial

install: true

services:
    - xvfb

addons:
    chrome: stable
    firefox: latest
    sonarcloud:
        organization: $SONARCLOUD_ORGANIZATION
        token: $SONAR_TOKEN

before_script:
    - export DISPLAY=:99.0

script:
    - mvn test -Dtest=ForceDownloadTest
    - bash <(curl -s https://codecov.io/bash)
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn sonar:sonar; fi
